### PR TITLE
Fixes for 1.14.0 compatibility

### LINKED ISSUE #69: Updates for 1.14.0 Compatibility
Work: Update the plugin so that it works with release 1.14.0.

### PR DESCRIPTION
**Pull request by dancastellon**
Resolves #69

## Fixes and changes
- Adjusting the fixtures so that the sticker's image is loaded correctly on first startup
- Created and used a new `<Link />` component on the homepage's tags block, so that the entire app is not reloaded when a featured tag is clicked
- Fixed featured product labels not displaying in grid
- Fixed the related products feature - When products are published, a "related tag" is created, that other tags can use to be marked as related to the published product
- Fixed all linting issues and removed some unused code
- Fixed sticker image not importing correctly on fresh install
- Fixed UI not scrolling to top when a similar product is clicked on PDP (and removed jQuery)
- Made footer email form only submit on enter press (not input blur)
- Linked the text in the header to the Github releases page (instead of a 404)

## Testing
1. Clone the main Reaction on this branch:`fix-dancastellon-method-hooks-async` (unless PR #4490 has been merged into 1.14.0)
2. Make sure the /private/plugins folder is empty
3. Clone this branch (`fix-ajporlante-1-14-0-compatibility`) into /imports/plugins/custom
4. Start Reaction with `METEOR_DISABLE_OPTIMISTIC_CACHING=1 SKIP_FIXTURES=1 reaction`
5. Confirm fixes/changes from above
6. Confirm overall better user experience with no bugs

### CODE REVIEW

File: client/containers/product-variant/productsContainerCustomer.js [hunk 1]
```diff
@@ -48,18 +44,6 @@ function composer(props, onData) {
     queryParams.query = queryString.query;
   }
 
-  // BOF: swag shop featuredProduct filter
```
Comment (dancastellon) [inline client/containers/product-variant/productsContainerCustomer.js]: @zenweasel I removed these few unused lines which were originally intended to limit the featured products on the homepage to 3. Instead, I linked the "Shop swag" button on the homepage to the "Products we love" section, which currently displays all published products. The "Shop swag" button previously did nothing. Let me know if this is a good user experience, or if we should instead create a "Shop" tag, have all products assigned to it, and link the hero button to that tag page.

**Comment by dancastellon** [comment]
@zenweasel How should we handle this PR? It requires [PR #4490](https://github.com/reactioncommerce/reaction/pull/4490) for the featured product labels to work, but that PR won't be merged until 1.15.

**Comment by ajporlante** [comment]
Amazing code here. Nice!
